# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaCopy' do
  pod 'DeepDiff'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstaCopy

  target 'InstaCopyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstaCopyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
